### ISSUE TITLE
Nopg could create not existing headpages

### ISSUE THREAD

**Issue by samuelet** [samuelet/indexmenu#106]
If any configured headpage exists, headpage fallbacks to the ":start" page even if it's not exists:
https://github.com/samuelet/indexmenu/blob/1ba8d3230a1504fccbc2ffa09020944e3e9fb569/syntax/indexmenu.php#L718

Removing this line fixes it, the drawback is that subtrees without headpages are not rendered (the worst case: the whole tree is not rendered if contains any headpage).

**Comment by Klap-in** [comment]
General note: the actual use case of nopg is not clear for me.

If _assuming_ an indexmenu tree should be navigable, it makes sense that _each node has a link_. Then it sounds reasonable to enforce a headpage for each namespace node. 
This ignored sofar the headpage setting. I implemented a guessing approach that uses the first enabled option in the headpage config setting. 

Default this is `:start: `, so for people using default settings, there is nothing changed. Others will see a change of the guessed headpage to the first setting enabled. (order is fixed, if a later one is needed, you need to disable the earlier options..)

Is there anything that can be improved further?

**Comment by Klap-in** [comment]
Added 'wikilink2' style to not-exiting headpages, to help recognizing the guessed pages.

If there are more points that needs attention, please reopen.
