### ISSUE TITLE
Failure to sort with msort

### ISSUE THREAD

**Issue by marphod** [samuelet/indexmenu#110]
I suspect that this is as much a feature request as it is a bug report.  I always end up doing things oddly. =)

I've got a indexmenu which I am attempting to sort by the default meta-tag.

```
{{indexmenu>:ssvv#1|msort}}

~~NOCACHE~~
```

I went through an added the tag to each of the pages (there are only 4, for now).  However, as I want to be able to insert pages in the index between the current ones, I numbered them 1, 11, 21, and 31.  

`{{indexmenu_n>1}}`
...
`{{indexmenu_n>31}}`

When browsing to any of the pages, I do get the "Indexmenu sort number: 31" (or whatever it should be for that page) notice.

However, the index order is : 31, 11, 1, 21.

This remains whether I use  javascript or not.  If I change to tsort or dsort, the order remains (which is wrong in both of these cases, as well).
(The order is correct in alpha-by-filename; that's it.)

I've cleared both my browser's cache and my server's cache, with no change.  Ditto with restarting Apache.

Ideas?

**Comment by rgleason** [comment]
what page do you put this code on?   sidebar?
{{indexmenu>:ssvv#1|msort}}
~~NOCACHE~~

We are putting 
{{indexmenu>:opencpn#1|js#drktheme navbar msort nsort}}
at the top of a namespace called "sidebar"

Under Configuration > indexmen
plugin»indexmenu»page_index
The page that will replace the main dokuwiki index. Create it and insert the indexmenu syntax. Use id#random if you already have an indexmenu sidebar with navbar option. My suggestion is {{indexmenu>..|js navbar nocookie id#random}}.

We have:  :opencpn:sidebar

**Comment by Klap-in** [comment]
Do you still experience this issue? I'm not able to reproduce it.
Extra info is welcome.
