### ISSUE TITLE
Conflict with Custombuttons plugin

### ISSUE THREAD

**Issue by mubed** [samuelet/indexmenu#114]
Having "Custombuttons 2014-12-10" and "indexmenu 2014-11-24" on DW 2012-01-25b "Angua" results in "Navigation tree is not displayed" issue (https://www.dokuwiki.org/plugin:indexmenu#the_tree_is_not_displayed).

**Comment by Klap-in** [comment]
Also reported here: https://github.com/ConX/dokuwiki-plugin-custombuttons/issues/28
But I cannot reproduce it.
