### ISSUE TITLE
Load root but expand specific namespaces

### ISSUE THREAD

**Issue by Braintelligence** [samuelet/indexmenu#115]
Hello everyone.

Maybe I just don't get how the syntax really works but what I want to do is this:

I want to show the whole root in the indexmenu but expand one specific namespace, let's call it specspace.

{{indexmenu>#1 [:specspace[#1]] | ... }}

It seems this syntax doesn't do this but how would I go about achieving that functionality? Is there even a way?

**Comment by samuelet** [comment]
Don't use the square brackets. Consider also to use the nocookie option:
{{indexmenu>:#1 :playground#1 | nocookie .... }}

**Comment by Braintelligence** [comment]
That helped, thanks a lot.
I couldn't figure out for the life of me how to interpret the basic syntax given on the dokuwiki page then, because there were brackets used there and no real example.

**Comment by samuelet** [comment]
square brackets means the setting is optional ;-)

**Comment by Braintelligence** [comment]
I see, but somehow I failed realizing how I should treat the bracketception correctly. There were other guides on the internet which suggested other syntax for this plugin altogether which confused me even more.
Thanks to you I understood how it works, thanks =).
