### ISSUE TITLE
Questions about styling the  indexmenu

### ISSUE THREAD

**Issue by Lukas-Schulte** [samuelet/indexmenu#116]
First of all, thanks for making this awesome plugin and sorry for probrably asking a stupid question.

I really like the indexmenu functionality, but want to change the style to match the rest of the wiki that I'm building.
 
Therefore, I'm trying to get rid of some of the icons. I know that I can just use empty icons and work from there in CSS, but layout wise it's a pain in the ass and I also want to move the icons to right side. 

Could you maybe point me to where in the code the icon  placement is conducted? Till now I've modified dTree.protype.node and dTree.protype.indent in indexmenu.js to only get the wanted icons as node.icon , but indexmenu now just places empty images for the unwanted icons like folder/folderh and so on. 

Thanks in advance, and again, sorry for a lazy question, I'm fairly new to web dev .

Cheers, Lukas

**Comment by Klap-in** [comment]
When you like to modify a theme, the simplest you can clone the original theme folder in the `[plugin dir]/indexmenu/images/` folder to a folder with the name of your own theme. (This way, it will also not be overwritten during an update of the plugin).
See also https://www.dokuwiki.org/plugin:indexmenu#javascript_themes

When you like to change some of the icons, you can now replace the images of these icons.
When you like to change the size of the icons as well, than you have to modify some css code.
To prevent mixing of the themes it is recommended to add a `style.css`to your theme folder, which modifies your spacing.
See also https://www.dokuwiki.org/plugin:indexmenu#css_style

Which class you need to use exactly is something what I don't now by heart. My advice is to check with the developer toolbar of Firefox or Chrome which elements you need for in your css.

If changes do not appear in your browser, you have to refresh some of the caching of browser and wiki.
Wiki: go to Config Manager, and just Save it. That will expire all current caching.
Browser: press Ctrl+F5

**Comment by Lukas-Schulte** [comment]
Thanks for your fast reply!

Yes, I'm aware of all this, I have created my own theme and everything, I'm just fairly new to web dev so I was looking for a way to get around replacing every icon that I don't want with empty images and enforcing my ideas of a layout through css and rather wanted to modify the code where the basic layout is created in the first place (I figured my noob-ish workarounds would only cause me major problems later on).  

Speaking of css, is there a reason why the larrow.gif is way bigger than the rarrow.gif? I mean it's of course easily fixable through css or changing the dimensions, I just couldn't figure out if there is an advantage of the different sizes that I'm not aware of.

**Comment by Klap-in** [comment]
I have no idea why the larrow is bigger than rarrow, but I haven't implemented that..
Maybe that @samuelet has an answer?

My first guess is that the right-hand side arrows are smaller so that these fit the line height of the text??

**Comment by samuelet** [comment]
Yes, to avoid unnecessary image size the righ arrow fits the line height, whereas the left one is bigger to fit better a minimal tree height.

**Comment by Lukas-Schulte** [comment]
Allright, thanks for your replies guys! I worked around it and ran into a more functional problem, but I'll open a new issue for that !
