### ISSUE TITLE
Display of child nodes with long names

### ISSUE THREAD

**Issue by Lukas-Schulte** [samuelet/indexmenu#117]
Hey, 

Now that I worked around the icon thing I have the following problem:

Due to fairly deep  namespaces and long page names some child nodes' names are too long for them to display within the given container , so usually the scroll arrows appear and everything's fine 
Sometimes, due to parameters unknown to me and a little more frequently on FF than on Chrome, when a child page with  a name that requires scrolling is selected, the very right of the pagename is displayed and the scroll arrows to the left aren't shown, so that one can not use the indexmenu to navigate anymore. This is visible on the following pictures. Is this a known bug? I only changed the theme and some css but nothing in the JS functionality. 
This is how it looks when it's not working:

![bad](https://cloud.githubusercontent.com/assets/9050085/7088276/b81206a4-df92-11e4-8ff3-aeb85aa039ba.png)

This is how it usually looks in those kinda cases (and should look)
![good](https://cloud.githubusercontent.com/assets/9050085/7088275/b81157a4-df92-11e4-8828-daa2157b8687.png)

It's not predictable for which pages this will happen, but it's reproducible for every page that it happens on. 

Thanks in advance! 

Edit: So I fixed my specific problem through preventing any sort of scrolling through restriction of the element sizes, but would in general prefer to have the option of scrolling

**Comment by bgx4k3p** [comment]
I am having the same issue. Can you provide any details on how to disable the scrolling and enable word wrap instead? Thanks!

**Comment by GJRobert** [comment]
I think the bug lies in the left scroll-back buttons. See how big they have become, and they are not clickable (no response, no scrolling back actually). I was going to raise a specific bug for this but I hope to raise some attention here instead at least.

**Comment by Klap-in** [comment]
The new JavaScript tree will not have a scroll function (work in progress in #230). Instead it shows tooltips on hover to tell the text of too long items.

**Comment by GJRobert** [comment]
> The new JavaScript tree will not have a scroll function (work in progress in #230). Instead it shows tooltips on hover to tell the text of too long items.

Looking forward to it. Thanks!
