### ISSUE TITLE
w3c validator: Element script must not have attribute charset unless attribute src is also specified.

### ISSUE THREAD

**Issue by ghost** [samuelet/indexmenu#118]
Checking page source code on w3c validator against html5, following error is shown: `Element script must not have attribute charset unless attribute src is also specified.` for

```
<script type='text/javascript' charset='utf-8'>
<!--//--><![CDATA[//><!--
```

**Comment by stefanscherzer** [comment]
Just remove **charset='uft-8'** to get this part valid.
The charset attribute specifies the character encoding used in an external script file.
Since you use no src, the charset is not needed.
http://www.w3schools.com/tags/att_script_charset.asp

**Comment by Klap-in** [comment]
All the inline JavaScript will be removed as part of #230.

**Comment by Klap-in** [comment]
Implemented, thanks for reporting. Sorry for slow response for an obvious fix.
