### ISSUE TITLE
expand a node when 'useheading' is used

### ISSUE THREAD

**Issue by KaiMartin** [samuelet/indexmenu#120]
I like the option to retrieve the entries in the index from the headers pages. But there is a flip side. If I activate this feature with the global setting 'useheading', a click on the node string does not expand the sub tree anymore. It shows the head page in the main area instead. To expand the tree I'd have to click on the icon in front of the string. 

Skipping through the manual I find that this the expected behaviour. Excerpt from the manual of the plugin, section "Namespaces title and link (headpages)": 

>  "Every namespace will retrieve its title from the heading title of that page, called headpage, and will be linked directly to it. **No longer you can open the node by clicking the header** (in the js version you can still use the plus before namespace)."

However, my users tend to not discover the ability to expand the tree by a click on the icon. Our content is nicely arranged in a tree of namespaces. So they miss an opportunity to easily navigate the wiki. Would it be hard to modify the plugin to make a click on the string of a node do both -- expand this node in the index and also show the corresponding head page?

Alternatively, is there a way to make the string behave exactly like the icon does now? That is, not open the header page but just expand the local branch?

---<)kaimartin(>---
PS: My dokuwiki sandbox is at http://bibo.iqo.uni-hannover.de/

**Comment by mbromley-voxel** [comment]
I'm struggling with this as well.  As a side bar menu I would like to be able to expand the name space to see the page as opposed to going to that page with the same title as the name space.  I've tried with the useheading option enable and disabled, but I get the same results.  Is it possible to have the non js version work the same as the js?  If I enable js I'm able to use the + sign to navigate through the namespaces and pages.

**Comment by Klap-in** [comment]
https://github.com/samuelet/indexmenu/issues/241 seems the same issue.

The base layout of the dokuwiki index is used for the 'nojs' version, but with the addition of clickable links, no interface element is remaining for opening the node.

**Comment by Klap-in** [comment]
> However, my users tend to not discover the ability to expand the tree by a click on the icon. Our content is nicely arranged in a tree of namespaces. So they miss an opportunity to easily navigate the wiki. Would it be hard to modify the plugin to make a click on the string of a node do both -- expand this node in the index and also show the corresponding head page?
> 
If I visit your site, this seems to happen now? You use/found already the `navbar` setting (`{{indexmenu>.#1 |js#index-iq.png tsort msort nsort notoc navbar}}`), which let expand the tree at the current page.

> Alternatively, is there a way to make the string behave exactly like the icon does now? That is, not open the header page but just expand the local branch?
>
I think by disabling the `headpage` setting. Then headpages are not recognized anymore and not use for linking, and the namespace nodes can only open and close.

> I like the option to retrieve the entries in the index from the headers pages. But there is a flip side. If I activate this feature with the global setting 'useheading', a click on the node string does not expand the sub tree anymore. It shows the head page in the main area instead. To expand the tree I'd have to click on the icon in front of the string.
>
 * I do not understand this completely: "retrieve the entries in the index from the headers pages" do you mean you have in the `headpage` setting the `:start:` checkbox enabled?
 * I did not found yet any relation between the `useheading` setting and whether the namespace node is autolinking a head page. My understanding is now that `useheading` will not influencing the autolinking to headpages.
