### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by johnjoepo** [samuelet/indexmenu#126]
I like your Plugin very much and would like to ask you if it's possible to add drag and drop functionality to the indexmenu, so if i drag and drop a page from the index in another folder in the indexmenu it is moved in there?

I would really love this feature!

**Comment by Klap-in** [comment]
Nice request, but too complex to combine with current techniques applied in this plugin.

For drag and drop moving with trees, you can use the admin interface of the Move Plugin.
