### ISSUE TITLE
Page-Scrolling when use in sidebar

### ISSUE THREAD

**Issue by moz0817** [samuelet/indexmenu#129]
When I use indexmenu in a the sidebar, the contentpages scrolls down.
This behavior accurs only if indexmenu shows also 'pages'. If I use the option 'nopg' within indexmenu, no scrolling happens.

Release 2015-08-10 "Detritus"
Templates: Dokuwiki, Starter
Browser: Firefox and IE

**Comment by Klap-in** [comment]
For the javascript version you could use the `noscroll` option to disable the scrolling. See also https://www.dokuwiki.org/plugin:indexmenu

**Comment by moz0817** [comment]
Not the sidebar within the index is scrolling. 
The main contentpage scrolls down!

**Comment by Klap-in** [comment]
That is a default feature of indexes in DokuWiki. It let you find quickly the current page in the index..
(especially useful at the Sitemap e.g. https://www.dokuwiki.org/dokuwiki?do=index , this moves to the dokuwiki page in the index.)

No idea when this feature is added...

**Comment by Klap-in** [comment]
Here it is added: f7dbf1759d3f9a578d8d84bda58bda7777ee7365

**Comment by moz0817** [comment]
I think you don't got the problem. 
What I mean is a new behavior probably since "Detrius". We discuss it already in https://forum.dokuwiki.org/thread/12867.

**Comment by Klap-in** [comment]
Yes, the change I pointed (i.e. splitbrain/dokuwiki@f7dbf17), is from December 2014, thus since Detrius included.
That change in DokuWiki causes your troubles of autoscrolling with the indexmenu.

Now we have to consider how we can come up with a solution...

**Comment by moz0817** [comment]
I have just change the function in file inc/html.php to the version shown in splitbrain/dokuwiki@f7dbf17.
Now everything seems wonderful. No scrolling. 
But I really don't now what I done ;-). I have no idea about the dokuwiki-core.

**Comment by Klap-in** [comment]
Fixed in the development version. See https://github.com/splitbrain/dokuwiki/issues/1314
