### ISSUE TITLE
error with edittable plugin

### ISSUE THREAD

**Issue by LMS235** [samuelet/indexmenu#132]
there seems to be an errror with the latest version of edittable plugin and indexmenu plugin

see https://github.com/cosmocode/edittable/issues/83

**Comment by micgro42** [comment]
It appears that indexmenu overwrites the constructor for [`Node`](https://developer.mozilla.org/en/docs/Web/API/Node) elements in [indexmenu.js](https://github.com/samuelet/indexmenu/blob/2b25b7eb94019c333e07a19b3decc903ae83806e/scripts/indexmenu.js#L41)
