### ISSUE TITLE
context option seems not works

### ISSUE THREAD

**Issue by wilsonlmh** [samuelet/indexmenu#135]
The `{{indexmenu>.#1|context}}` not works.
What I expect(and my understanding) `{{indexmenu>.#1|context}}` will equal to `{{indexmenu>.:subns#1|}}` while im in index page of `.:subns`(correct me plz). However it doesn't works on my environment. My config:
dokuwiki 2015-08-10 Detritus
win2012/iis8 + php5.5
indexmenu 2015-08-26
all parameter for indexmenu leave empty/disabled except `aclcache = none`, `headpage = all` and `show_sort = yes`
I didn't dig too deep into code(actually i dun understand the code and dun have time to read default methods from dokuwiki ). I did a cache flushing with `cacherevisionserase` plugin. and tried many way to delete/flush unwanted thing after backup but no luck. I know the context option was added since 2009. The possibility for something wrong inside your code is quite low. So is that any prerequisites needed for this? please help and thank you!

**Comment by Klap-in** [comment]
context is meant for the sidebar, if you visit another page then the sidebar, the indexmenu should consider the namespace of you current page, not the namespace of the sidebar-page.

**Comment by Klap-in** [comment]
No further feedback received, considered solved.
