### ISSUE TITLE
hide_headpage is enabled, headpage still appears

### ISSUE THREAD

**Issue by mambojuice** [samuelet/indexmenu#145]
I have hide_headpage enabled in my configuration settings, however all namespace :start pages are still appearing.

The below screenshot is showing the page listing under a VMware namespace I have created. The following code was used to generate the menu:
{{indexmenu>.:#1|pg nons}}

As you can see the namespace start page still appears in bold.

![hide_headpage](https://cloud.githubusercontent.com/assets/9440225/12309367/3e16f0a6-ba18-11e5-8134-5b4a5299b1e0.png)

**Comment by dennisverspuij** [comment]
From the code I see `hide_headpage` is effectively ignored when `nons` is specified. I am not sure whether this makes sense or not.

**Comment by Klap-in** [comment]
The logic behind it is that if you use `nons`, the tree will not show namespace-nodes at all and only page nodes (including the pages at lower level, which you have prevented effectively with the `#1`. The `headpage` setting will default search for the different types of head pages (:start:, :inside: and :same:) and autolink the namespace name to it. The `hide_headpage` setting prevent the duplicates appear in the tree another time. If you have no namespace-nodes, the tool cannot display that headpage link anymore. Therefore, the headpages are not hidden, to prevent that they get lost. 

Alternative is to use the skipfile option with an regexp that hide the start pages.

**Comment by Klap-in** [comment]
Closing this, as `skipfile` option is available to achieve this.
