### ISSUE TITLE
indexmenu does not work - js problem with vector template?

### ISSUE THREAD

**Issue by Henry31** [samuelet/indexmenu#15]
Hey,

i installed my dokuwiki Weatherwax RC1 with the vector template. After that i installed your indexmenu plugin but it didn´t work fine...
Here is a screenshot:
![indexmenu js_error](https://f.cloud.github.com/assets/4036303/328042/a0308176-9b8a-11e2-91b3-abf075c53489.png)

This is the syntax:
{{indexmenu>..|js#bj-tango.png navbar}}

With the default templates i didn´t work also...

Indexmenu Version: 2009-08-29

Can you help me?

Thanks a lot.
Henry (Germany)

**Comment by atlarep** [comment]
I have this same issue but on Internet Explorer only. 
The console does not show any errors, but all I get is text in the nav box.
