### ISSUE TITLE
page not listed, when named same as parent directory

### ISSUE THREAD

**Issue by 400thecat** [samuelet/indexmenu#158]
when I create 3 pages inside foo/ directory:

```
foo/start.txt
foo/test.txt
foo/foo.txt
```
and have indexmenu in start.txt:

```
$ cat foo/start.txt
{{indexmenu>.#1}}
```
when I go to http://www.example.com/foo/

I only see page named test.
The page named foo is not shown

**Comment by Klap-in** [comment]
A guess by heart: does the `nons` option help? or is that too much?

**Comment by 400thecat** [comment]
When I use `nons` in start, I then see `foo` twice:

```
foo
foo
test
```
whereas, these link to, respectively:

```
foo/foo
foo/start
foo/test
```

**Comment by Klap-in** [comment]
Hmm, the title of the link is depending of the settings for the heading.
https://www.dokuwiki.org/plugin:indexmenu#namespaces_title_and_link_headpages

Hmm. Instead of 'nons' option, you will have a look at the setting values of the `hide_headpage` and `heading

**Comment by 400thecat** [comment]
OK, I have unchecked following two options in the configuration manager, and that solved the problem for me:

  :inside: (A page with the namespace name and that is inside it)
  :same: (A page with the namespace name and that is at its same level)

maybe these options should be unchecked by default?
It is not very intuitive to me, why foo/foo page should be hidden

Is there any usefulness in this, that I am missing ?

Thanks anyway, for the super fast help

**Comment by Klap-in** [comment]
This plugins has a lot of defaults, which might updated indeed to other values imho if you consider current state of features of this plugin. But that would break backward compatibility as well... so therefore I didn't do it so far...
