### ISSUE TITLE
Issue in the sidebar

### ISSUE THREAD

**Issue by zydar16** [samuelet/indexmenu#161]
hi, 

i don't know if it's happened because of config or php server update, but i obtain this error on my sidebar sometimes ... If anyone has an idea it will be great :)
`Warning: preg_match(): Unknown modifier '|' in /var/www/wiki/lib/plugins/indexmenu/syntax/indexmenu.php on line 680
`

**Comment by Klap-in** [comment]
Some questions for more context:
 1. Which syntax are you using in your sidebar?
 1. What is filled in the field of the configuration setting 'skip_index' of the indexmenu plugin in the Configuration Manager (reachable via admin menu)?

**Comment by zydar16** [comment]
Hi, 

1. I use : {{indexmenu>.#2|skipns=/(test)/|sneaky_index=disabled}}

2. "plugin»indexmenu»skip_index" is empty ? Is that normal ? :o

**Comment by Klap-in** [comment]
`|` should be used once, the options for the indexmenu are separated by spaces.
eg.: `{{indexmenu>.#2|skipns=/(test)/ sneaky_index=disabled}}`

Note that [sneaky_index](https://www.dokuwiki.org/config:sneaky_index) is only a dokuwiki configuration setting, and not an indexmenu syntax option.

Could you try: `{{indexmenu>.#2|skipns=/(test)/}}`
