### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by mausampaio** [samuelet/indexmenu#163]
I'm trying to create a theme and would like to modify the contextmenu, all changes made via CSS did effect, but can not find the place to change some strings.

I tried to create a new folder on indexmenu / lang but it does not change anything. I tried to make changes in contextmenu.local.js but without success.

Even tested delete the file "contextmenu.js" and it continued showing everything normally. Where can I make these changes?

Thank you.

**Comment by samuelet** [comment]
Default values are stored in the $lang['js'] hash in indexmenu/lang/XX/lang.php

According to https://www.dokuwiki.org/devel:localization it can be customized in 
\<dokuwiki\>/conf/plugin_lang/\<pluginname\>/\<language\>/lang.php

**Comment by Klap-in** [comment]
Already answered.
