### ISSUE TITLE
"navbar" doesn't work properly with "nopg" in Javascript mode

### ISSUE THREAD

**Issue by mightymt** [samuelet/indexmenu#164]
When ```navbar``` and ```nopg``` options are used together in Javascript mode, the tree doesn't always open to the current page's namespace.

Take for example a wiki that has the following namespace structure...

```
root
|- level_1
|  |- level_2
|     |- sample_page
|     |- start
|- sidebar
```

... and the following indexmenu syntax in the sidebar...

```
{{indexmenu>.#1|js navbar nopg}}
```

Now when you view the page ```level_1:level_2:start```, the tree will be opened to the ```level_1:level_2``` namespace automatically, however when you view the page ```level_1:level_2:sample_page``` it won't.

The problem is that the [openCurNS function](https://github.com/samuelet/indexmenu/blob/master/scripts/indexmenu.js#L572) always compares the entire page ID, which works fine without the *nopg* option (i.e. when the page ```level_1:level_2:sample_page``` itself is also in the indexmenu tree) but otherwise doesn't.

By the way, I have the ```headpage``` config option is set to *:start:*

**Comment by Klap-in** [comment]
Implemented in the new javascript tree. Use `{{indexmenu>.#1|js navbar nopg treenew}}` as long this js tree is not yet default.
(implementing in the old tree as well is too much work for me)

**Comment by mightymt** [comment]
@Klap-in Thank you. The new tree seems to be functioning great and fixes this issue.
