### ISSUE TITLE
Background does not inherit style or color

### ISSUE THREAD

**Issue by Valiantiam** [samuelet/indexmenu#165]
![image](https://cloud.githubusercontent.com/assets/5394853/20536952/cb3e4544-b0b0-11e6-9af8-5d9aa47fe55c.png)

With darker themes (This is using bootstrap)

the background is not inheriting the background color and this is causing darker themes to not be readable. Can this be corrected?

**Comment by samuelet** [comment]
Indexmenu themes can be customized according to your own needs:
https://www.dokuwiki.org/plugin:indexmenu#javascript_themes

**Comment by Klap-in** [comment]
Is the illustration of an indexmenu? Which background do you mean?
