### ISSUE TITLE
Need @manager group to be able to add, edit and save indexmenu sort code

### ISSUE THREAD

**Issue by rgleason** [samuelet/indexmenu#167]
https://forum.dokuwiki.org/thread/14221
I have a new User/Editor who is wiping out the {{indexmenu_n>4}} sort code at the top of the page each time he saves the page.

I found a partial solution: Changed the user's acl permissions from @manager to @admin.
This solves the problem now.  The user can edit and save the Indexmenu Sort Code.

Does this give any suggestion as to what the problem might be?
Does some directory or file need different permissions?

I would like to have @manager group be able to add, edit and save the indexmenu sort code.

**Comment by samuelet** [comment]
Permission to insert the sort tag is allowed to dokuwiki admin (isadmin variable) and is managed here:
https://github.com/samuelet/indexmenu/blob/2f40fa871af02db9c14dbf2ee97e67285bdc2b00/action.php#L35
You can try to change isadmin with ismanager.
If it works as expected, it should be easy to add a new indexmenu option to extend this permission.

**Comment by Klap-in** [comment]
Is it not simpler to just allow managers as well, instead of only admins?
Is it really important to restrict it to only admins? (I think this is minor enough to ignore the backward compatibility)

This plugin has already a lot of options. So if we can avoid another one, that is win IMHO :)

**Comment by samuelet** [comment]
My first thought was on users/groups management especially in big sites where indexmenu can slow down the service, but probably it's a premature thought at this time. 
Giving permission to both groups it seems to me, in the same way, a good solution.

**Comment by rgleason** [comment]
Thanks very much.
