### ISSUE TITLE
Custom icons for pages and namespaces

### ISSUE THREAD

**Issue by Myppomeu** [samuelet/indexmenu#169]
It would be wonderful if I can edit icon for every single folder. It will help find needed page much quickly than now.

**Comment by Klap-in** [comment]
How should the indexmenu plugin choose its icons according your wishes? Depending on the file name? 

I do not understand which logic is here. So please explain, or illustrate?

**Comment by Myppomeu** [comment]
For example, I have page named "Linux" and uploaded icon "tux.png". After assigning "tux.png" to "Linux" page it would look like this:
![example](http://i85.fastpic.ru/big/2016/1206/d2/4a92b7c780cd3f4e74e18f1d5ab159d2.png)
Assigning can be done with context menu of page (in sidebar).
Don't know if this can be realized, just proposal.

**Comment by Klap-in** [comment]
If it is set manually, it should be stored somewhere. The first place to store it, is as config setting in the syntax of this plugin. 

If it is not stored as config setting in the syntax, then another settings storage should be used. This makes this feature request laborious. So I won't implement this.

Further the purpose of the indexmenu is to prevent building of lists/indexes of pages/namespaces manually. Having manually layouting options per page is against this logic. Therefore I suggest to close this request.

**Comment by Myppomeu** [comment]
It can be realized like {{indexmenu_n>N}} syntax: just some tag in source of page that specifies icon.

**Comment by Klap-in** [comment]
Ah, I didn't think about that possibility. Good solution.
Pull requests are welcome.

**Comment by Klap-in** [comment]
I will not implement this, as it is too much work. If someone interested do not hesitate to discuss and propose a pull request.
