### ISSUE TITLE
First Letter of Namespace Capitalization

### ISSUE THREAD

**Issue by revmwv** [samuelet/indexmenu#170]
This is probably something really simple, but I am just not getting anywhere. When I created my namespaces I create them like this "Namespace", but they show up as "namespace" in the menu. I cannot figure out why it is not holding the capitalization of the first letter for the menu. But when I see other examples around the web, the first letters are capitalized. So is there a setting I missed or something? Any help is greatly appreciated!

**Comment by mkzero** [comment]
You could either run the title through something like `uc_first` or just have a headline on every page and use that for menu entries via [config:useheading](https://www.dokuwiki.org/config:useheading) - which would give you full control over the menu entry.

**Comment by Klap-in** [comment]
There are a lot of settings. No idea to which indexmenu appearance you are looking. Please reopen with syntax example.
