### ISSUE TITLE
Does not work with JS in release 2017-02-19b "Frusterick Manners"

### ISSUE THREAD

**Issue by sorenweber** [samuelet/indexmenu#175]
After having upgraded, my sidebar does not display the navbar properly.
The code is `{{indexmenu>.#3|js#leopard navbar skipfile+/[ci]_template/}}` and the (first part of the result looks like this: 
`<!--//--><![CDATA[//><!-- var indexmenu_207313865958fdc41123327 = new dTree('indexmenu_207313865958fdc41123327','default'); indexmenu_207313865958fdc41123327.config.urlbase='/doku.php?id='; indexmenu_207313865958fdc41123327.config.sepchar=':'; indexmenu_207313865958fdc41123327.config.jsajax='%26skipfile%3D%252B/%255Bci%255D_template/'; indexmenu_207313865958fdc41123327.add('q',0,-1,"q",'q:start'); indexmenu_207313865958fdc41123327.add('q:departments',1,0,"departments",0,1,0); indexmenu_207313865958fdc41123327.add('q:departments:design_projects',2,1,"design_projects",'q:departments:design_projects:start',1,0); `

Having experimented a little it looks like it is the javascript that causes a problem.

How it should look (and did prior to upgrade):
![image](https://cloud.githubusercontent.com/assets/6850199/25330739/f8c1bf3e-28e0-11e7-8a06-ac9678513bbb.png)

How it looks after the upgrade:
![image](https://cloud.githubusercontent.com/assets/6850199/25330788/1c9e6308-28e1-11e7-85d1-b9187e91110b.png)

**Comment by poeschke** [comment]
I am facing exactly the same issue with my installation. 

When loading or refreshing the page, the Indexmenu gets displayed for about half a second correctly, then gets replaced by the source code fragment shown above.

**Comment by sorenweber** [comment]
Having tested with the default dokuwiki template and seeing it working, I believe the issue is with the template I use, rather than with the indexmenu extension itself. Thus, one whould look into updating templates if this issue is encountered.
