### ISSUE TITLE
Index menu : js#ggo navbar tsort msort nsort notoc noscroll

### ISSUE THREAD

**Issue by elassabe** [samuelet/indexmenu#176]
I have this problem with the indexmenu's 4.6 plugin in DokuWiki. Instead of having the index on the left hand size,  I have this message:
Js # ggo navbar tsort msort nsort notoc noscroll

And when cliking on it, it opens this url [](https://wiki.galigeo.com/lib/exe/fetch.php?media=indexmenu#2) that says "Not found"

Strange things, I tried to host the wiki locally on my machine (just copied the files over it) and it works just fine. 
Any idea what could be the problem?

Thanks

**Comment by Klap-in** [comment]
Did you install a plugin that interfere with the syntax of the Indexmenu plugin?

**Comment by elassabe** [comment]
Not for the moment ! And I didn't understand what's happened ?

**Comment by Klap-in** [comment]
but... 4.6, what means that?
That you have a really old version of the plugin?

**Comment by elassabe** [comment]
Surely, I think ! But I try and it's not working with my Dokuwiki's version !

**Comment by Klap-in** [comment]
Ah, you are still sticking to an old version of DokuWiki?

Sure the syntax is right? 
How does it appear, do you have a screenshot maybe?

**Comment by elassabe** [comment]
It appears like that
![ggo-wiki](https://cloud.githubusercontent.com/assets/29043333/26717925/6dce1ef0-477f-11e7-9bde-6a706cdbc440.PNG)

**Comment by Klap-in** [comment]
Is it enabled in the Plugin Manager?

**Comment by elassabe** [comment]
Yes, but when I reinstall, it works. Thanks, for your help...

**Comment by Klap-in** [comment]
ok nice!
