### ISSUE TITLE
Very hard to scroll back (left)

### ISSUE THREAD

**Issue by GJRobert** [samuelet/indexmenu#180]
Hi there,

I still like the scroll feature, but ever since I started to use this plugin (2016), the left "Click to scroll back" arrow buttons are very hard to click... they hardly respond to my clicks (maybe 1 out of 10 clicks), and since the menu only scrolls back 1 px per click... The menu becomes very slow to scroll left.

I'm encountering this on a MacBook, on both Firefox/Pale Moon and Vivaldi/Chrome browsers. If you too are encountering this problem please kindly speak up.

![Left arrow buttons hardly respond](https://imgur.com/9KvOS0G.jpg)

I have tried to tweak in ``/scripts/indexmenu.js``, line 178:
```javascript
        str += '<div id="left_' + this.obj + '" class="indexmenu_larrow" style="display:none;" title="Click to scroll back" onmousedown="javascript:' + this.obj + '.scroll(\'r\',1);" onmouseup="javascript:' + this.obj + '.stopscroll();"></div>';
```
change ``.scroll(\'r\',1);`` to ``.scroll(\'r\',10);`` or something, but it does not help yet.

**Comment by GJRobert** [comment]
I found today that this issue happens on macOS (every browser), not on Windows. Perhaps that's why there not so many people having this issue.

**Comment by Klap-in** [comment]
Looking at benefit, complexity and maintainability it is too much effort for me (as one of the maintainers of this plugin) to improve this code.  Personally I would even remove this feature to reduce the complexity of this plugin. However I understand that there are peoples that would prefer this kind of features. 

So maybe there are other people using this plugin who have nice ideas to improve this situation?

**Comment by GJRobert** [comment]
Hi Klap-in,

Thank you so much for replying. I know very little about coding, but I'm willing to help searching for solutions. Could you or anyone provide the related methods or functions in the code to look into, so that I might find why the function does not work on macOS? May I just look in indexmenu.js, or should I look in other script files too?

**Comment by TorMec** [comment]
> Personally I would even remove this feature to reduce the complexity of this plugin.

... or it could become an option so that it can be disabled if it doesn't work.

**Comment by Klap-in** [comment]
You can disable this scrolling by using 'noscroll' option. Eventually you can set it in the configuration manager as default for all indexmenu's.
https://www.dokuwiki.org/plugin:indexmenu#syntax

**Comment by Klap-in** [comment]
As part of this #230 the scroll feature will be removed.
