### ISSUE TITLE
Сreate nested menus, but without the need to create a sub-namespace

### ISSUE THREAD

**Issue by SergeySCHU** [samuelet/indexmenu#186]
Is it possible to add a new functionality that will allow to create nested menus, but without the need (for various reasons) to create a sub-namespace for this. This would be, as it seems to me, a good addition to the functional of indexmenu. If you want I will give an example.

**Comment by samuelet** [comment]
Yes, could you provide an example ?

**Comment by SergeySCHU** [comment]
For example, I attached two screenshots:
№1 - namespace without nested spaces
№2 - namespace with nested spaces

![1](https://user-images.githubusercontent.com/34894453/40630483-b1820e36-62db-11e8-8532-411c792103e7.png)              ![2](https://user-images.githubusercontent.com/34894453/40630491-b9c69a26-62db-11e8-90fb-064b033c8a42.png)


I think it would be convenient to be able to make the menu display as on the image №2, but without creating subspaces ie. as №1

this could be made a new operator in the syntax in which the indexes or page names would be listed, etc.
For example, on the Part1 page, write
{{indexmenu_collapse_n> 101-103}} where 101-103 sorting indexes
or
{{indexmenu_collapse> 1.1,1.2}} where "1.1", "1.2", "1.3" page names

or in some other way, after which the Part1 page would look in the menu as a namespace, not being such

**Comment by SergeySCHU** [comment]
upd

**Comment by Klap-in** [comment]
If you choice your namespaces and page ids such that these order correct, you can sort the indexmenu on page id.
If you have headlines/titles with numbers you can sort on title (`nsort tsort`).
(For numbered headlines you could consider https://www.dokuwiki.org/plugin:numberedheadings as well)

Further it looks like a very confusing feature for a lot of users, and too much work to implement my self.
