### ISSUE TITLE
indexmenu stop working after update to 2018-04-22 "Greebo"

### ISSUE THREAD

**Issue by rtzra** [samuelet/indexmenu#187]
indexmenu stop working after update to 2018-04-22 "Greebo"

**Comment by jobhh** [comment]
Seems fine here. Maybe you should post more information and a couple logs ;)

**Comment by bakern** [comment]
@rtzra what part of the indexmenu plugin isn't working, or did you get it figured out?

I had the navbar functionality stop working after a similar upgrade, and found that the jQuery call to initialize the indexmenu wasn't executing anymore.

After changing the call in indexmenu.php (https://github.com/samuelet/indexmenu/blob/master/syntax/indexmenu.php#L482-L489) it seems to work fine now, just wondering if it's affecting others, I can submit a pull request if so.

**Comment by irenewang0** [comment]
I upgraded dokuwiki to 2018-04-22 "Greebo"，sidebar indexmenu stop working 。Dokuwiki sidebar will render all pages under pages in the list。For example,this is my data structure。

![_50edc6b0-cef4-49f7-893a-a772cf1ff0d4](https://user-images.githubusercontent.com/24269936/63439885-78426600-c461-11e9-8fc9-64e621193a4e.png)

When I visit http://xxx.com/listA/listA-1/1.1/.., the sidebar only wants to display the pages below listA-1，but now shows all the pages。
{{indexmenu>:#4}}

**Comment by yuxesd** [comment]
I upgraded dokuwiki to 2018-04-22 "Greebo"，sidebar indexmenu stop working 。Dokuwiki sidebar will render all pages under pages in the list。For example,this is my data structure。

![_50edc6b0-cef4-49f7-893a-a772cf1ff0d4](https://user-images.githubusercontent.com/24269936/63439885-78426600-c461-11e9-8fc9-64e621193a4e.png)

When I visit http://xxx.com/listA/listA-1/1.1/.., the sidebar only wants to display the pages below listA-1，but now shows all the pages。
{{indexmenu>:#4}}

**Comment by Klap-in** [comment]
Not clear if there was an issue, or unlucky caching...
