### ISSUE TITLE
Limit Number of Pages and Display most Recent

### ISSUE THREAD

**Issue by mbromley-voxel** [samuelet/indexmenu#188]
I have some namespaces that have a lot of pages in them, most of them being legacy information.  Currently when the namespace is expanded in the navbar it will fill the whole left side of the screen with page titles.  An option to limit the number of pages displayed for a namespace and sort by page creation date so that only the most recent pages are shown would be great.  A plus symbol could be shown after the last page in the nav bar if the user wants to see more than the most recent content.

**Comment by Klap-in** [comment]
Looks like a bit more complex task to add, especially on the user interface side.

**Comment by Klap-in** [comment]
I will not add this to the indexmenu plugin. Probably there are plugins that can load recent changes from a namespace that fit better here.
