### ISSUE TITLE
how to refresh the tree after manually adding a file in data/pages ?

### ISSUE THREAD

**Issue by sebastienPoussard** [samuelet/indexmenu#191]
i'm developping a plugin to manually add txt files to /doku/pages 
i can see the file and access it into dokuwiki but the indexmenu list of files won't refresh.

How to do so ?

**Comment by samuelet** [comment]
https://www.dokuwiki.org/devel:caching#plugins has detailed info about cache management

**Comment by Klap-in** [comment]
Sometimes it is enough add once `?purge=true` or `&purge=true` to the url of you page.
Otherwise caching is reset if you use the Save in the Configuration Manager.
