### ISSUE TITLE
Question: Is there a way to pipe Indexmenu TOC to a simple text file, in Windows?

### ISSUE THREAD

**Issue by rgleason** [samuelet/indexmenu#192]
Example that I want to pipe to get hard copy of the code (dokuwiki) so that I can use it in EPUB.

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:toc

**Comment by Klap-in** [comment]
Question unclear. Please explain for example in steps what you need. At the moment I wonder if it should be implemented in this plugin.

**Comment by Klap-in** [comment]
Is your question that you just like to have the html of a page including the html of index created by the indexmenu?

In that case you can use a nojs indexmenu on a page, which you export with 
html plus layouting
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:toc&do=export_xhtml
more raw html:
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:toc&do=export_xhtmlbody

This the most I can make from your question. Please explain if still needed.
