### ISSUE TITLE
Template for headpage

### ISSUE THREAD

**Issue by froschl** [samuelet/indexmenu#197]
I often use the option "Create headpage here", it's very fine
but it seems it not respects the _template.txt.
Is there another template for that?
I would like to use  a templates for the headpage as for example

====== @PAGE@ ======
 {{indexmenu>.#0}} 

greetings,

froschl

**Comment by Klap-in** [comment]
`_template.txt` is working only in current namespace, not in higher or lower subnamespaces.
If you need template in a lower namespaces then `__template.txt` should be used.

**Comment by Klap-in** [comment]
Which template is used is a default feature of DokuWiki, not related to the Indexmenu plugin, so therefore closing.
