### ISSUE TITLE
BUG: sorting doesn't work, any of them

### ISSUE THREAD

**Issue by AureleCollinet** [samuelet/indexmenu#198]
Hello, i am using indexmenu for my sidebar. all option seems to work relatively fine. But when i try to sort my index, the menu isn't updated: i need to order my menu by importancy of the files, so i set 

a) repo1 ==> file name repo1.txt
b) repo2 ==> file name repo2.txt
c) repo3==> file name repo3.txt

i got the good info in my metadata title and even hid but the menu ins't updating at all.

![what i get](https://user-images.githubusercontent.com/35695327/52222336-966cbe00-28a3-11e9-9e33-34f4fa980a3b.PNG)

their is hsort written here but i just want to tsort the index
i tried msort#hid, msort#title it didn't work either.

i got this error: 

![bugbug](https://user-images.githubusercontent.com/35695327/52224188-af776e00-28a7-11e9-826d-381e9c0c9445.PNG)

**Comment by Balduin94** [comment]
i tried msort#hid, msort#title it didn't work either

**Comment by mbromley-voxel** [comment]
I'm using:

{{indexmenu>.:#1|navbar nsort msort js#kde}}

And it is working for me.  At the top of each page I use:

{{indexmenu_n>4}}

Where I increment the number as necessary.

**Comment by Klap-in** [comment]
I don't understand the case @AureleCollinet is describing. But a first impression is that it is an attempt to namespaces. For sorting namespaces you need to add `nsort`.

**Comment by Klap-in** [comment]
Probably the examples and suggestions could help already. Closing as no further action seems needed.
