### ISSUE TITLE
JS index loads very slowly -> replace image loading

### ISSUE THREAD

**Issue by zioth** [samuelet/indexmenu#21]
A large menu loads very slowly because there are so many images. While it's loading, it's too tall, and then it collapses down. Two things can be done to fix this:

1) Specify width and height of all IMG tags. For example `<img width="8" height="8" src="icon_plus.gif">`

2) Use CSS backgrounds instead of IMG tags. This will allow DokuWiki (Anguna or higher) to convert the images to inline CSS, which will make it immensely faster. For example:

<div class="indexmenu_icon_plus"></div>

CSS:

```
.indexmenu_icon_plus {
  display:inline-block;
  width:8px;
  height:8px;
  background-image:url(icon_plus.gif);
}
```

**Comment by Klap-in** [comment]
There is a new JavaScript tree based on Fancytree introduced (use `treenew` option, before it becomes the default). It uses sprites or font icons. I expect this must bring improvements. However, maybe I will replace the icon fonts by a limited set of svg icons that are included with the plugin, that needs probably some attention regarding this topic.
