### ISSUE TITLE
Feature Request: Add 'Open in New Tab' to context menu

### ISSUE THREAD

**Issue by lizat** [samuelet/indexmenu#211]
It would be really useful if this cold be added to the context menu because one doesn't always want to lose the current page. There may be other additions that are useful such as Open in new window, and copy link.

Thank you for a Fab plugin!

p.s Apologies if I have asked this somewhere already (can't find it although I was sure I had)

**Comment by gix** [comment]
Why not just click the menu link with the middle mouse button (or ctrl-click)?

**Comment by Klap-in** [comment]
That solution makes sense.

**Comment by lizat** [comment]
Yes, of course one can do that but I was thinking it would be convenient if on the context menu... anyway as you wish
