### ISSUE TITLE
Feature Request: Add a parameter to offer Expand-Collapse All

### ISSUE THREAD

**Issue by lizat** [samuelet/indexmenu#212]
I thought I had seen this as an option but cannot find it (apologies if it does in fact exist).

Could be a config parameter with an override parameter in the syntax

**Comment by Klap-in** [comment]
This feature does already exists:

Show all nodes opened `{{indexmenu>yournamespace}}`

Show only first level of nodes opened `{{indexmenu>yournamespace#1}}`
Show only first two levels of nodes opened `{{indexmenu>yournamespace#2}}`
