### ISSUE TITLE
HTTPClient not found

### ISSUE THREAD

**Issue by phy25** [samuelet/indexmenu#214]
```
Fatal error: require_once(): Failed opening required '/dokuwiki/inc/HTTPClient.php' (include_path='\php\PEAR') in \dokuwiki\lib\plugins\indexmenu\admin.php on line 11
```

Edit: forgot to say this is on master branch of DokuWiki which will be released soon.

**Comment by xaozai** [comment]
I have the same problem :(

**Comment by splitbrain** [comment]
The proper fix is to not manually require the file at all. Let DokuWiki's autoloading take care of it.

**Comment by JohannesKleine** [comment]
changed the pr accordingly and is still working :-)
