### ISSUE TITLE
JavaScript themes don't work

### ISSUE THREAD

**Issue by xaozai** [samuelet/indexmenu#215]
I use this code on my sidebar
```
\\ \\ \\ 
----
{{indexmenu>:#3 |js skipns=/en|playground/ :inside: nocookie navbar dsort nsort}}

~~NOCACHE~~
```
and I tried to do this:
```
{{indexmenu>:#3 |js#drktheme skipns=/en|playground/ :inside: nocookie navbar dsort nsort}}
{{indexmenu>:#3 |js#bj-tango.png skipns=/en|playground/ :inside: nocookie navbar dsort nsort}}
{{indexmenu>:#3 |js#default skipns=/en|playground/ :inside: nocookie navbar dsort nsort}}
```
And nothing changes. The menu is displayed exactly the same as without js at all.
What could be the reason for this?

There are no errors in `/var/log/nginx/error.log`

**Comment by spigotx** [comment]
Same here.
`{{indexmenu>: .:start#3|js#shiki_brave.png tsort}}`

JS menu doesn't work and the menu is expanded.

No error in logs.

**Comment by 4001982248998** [comment]
same here, with the simplest

```
{{indexmenu>.#1|js}}
```

**Comment by Klap-in** [comment]
Defering of Javascript is added to DokuWiki. The indexmenu plugin is not yet updated to handle this. You can temporary disable it using the feature flag ‘defer_js’ in the config manager of DokuWiki.

https://www.dokuwiki.org/config:defer_js
Introduced in: https://github.com/splitbrain/dokuwiki/pull/2974

**Comment by Klap-in** [comment]
An message for the users is added, to find the workaround for this issue. https://github.com/samuelet/indexmenu/commit/481a3cf8ef5cd438582902b1901edda0b7491b30

Long term fix is arriving via: https://github.com/samuelet/indexmenu/issues/230
