### ISSUE TITLE
blank admin page after upgrading dokuwiki

### ISSUE THREAD

**Issue by dragonauta** [samuelet/indexmenu#216]
Hi, I was dealing with dokuwiki upgrade.
After disabling all plugins and switched back to default template, upgrading dokuwiki to Hogfather was smooth, everything works except for indexmenu plugin.

Enabling indexmenu results in a blank admin page.
Can't find any message in logs.
How can I add more info to resolve this issue?
Thanks

**Comment by bradleeriley** [comment]
Hello,

I am receiving the same issue. Blank admin panel. Removing the indexmenu plugin resolves the issue.

error.log shows the following error:
`[Tue Jun 02 11:07:33.819786 2020] [php7:error] [pid 24935] [client 192.168.251.196:65089] PHP Fatal error:  require_once(): Failed opening required '/var/www/dokuwiki/inc/HTTPClient.php' (include_path='.:/usr/share/php') in /var/www/dokuwiki/lib/plugins/indexmenu/admin.php on line 11, referer: https://dokuwiki.website.com/doku.php?id=start`

**Comment by alexgann** [comment]
yeah, the new dokuwiki version moved that path to /inc/HTTP/HTTPClient.php.  Guess they'll need to check for existence of one and fallback to other, or check dokuwiki version and set path accordingly in admin.php.

Also in action.php getting an error at line 161 for require_once of inc/JSON.php - looks like they removed that module altogether.  I just removed that import and am using PHP's native `json_encode` and seems to be working alright

**Comment by alexgann** [comment]
One other note for @samuelet and other users - you will need to set the new `defer_js` feature in your Config to False (unchecked) or your sidebar collapsible behavior won't work.

**Comment by Klap-in** [comment]
Please focus the discussion to one issue per issue. Could you open an specific issue? It needs some refactoring indeed. Thanks!
