### ISSUE TITLE
Indexmenu doesn't collapse after update to Release rc2020-06-01 "Hogfather"

### ISSUE THREAD

**Issue by Vudubond** [samuelet/indexmenu#219]
Hello,

The Indexmenu doesn't collapse after update to Release rc2020-06-01 "Hogfather".

dokuwiki template used.

In console shows 

doku.php:131 Uncaught ReferenceError: dTree is not defined
    at doku.php:131
(anonymous) @ doku.php:131

Please help.

**Comment by revol** [comment]
That fixed this issue for me for now:
> Defering of Javascript is added to the upcoming version of DokuWiki. The indexmenu plugin is not yet updated to handle this. You can temporary disable it using the feature flag ‘defer_js’ in the config manager of DokuWiki.
> 
> https://www.dokuwiki.org/config:defer_js
> Introduced in: https://github.com/splitbrain/dokuwiki/pull/2974

_Originally posted by @Klap-in in https://github.com/samuelet/indexmenu/issues/215#issuecomment-638049353_

**Comment by Vudubond** [comment]
Yes please it is working with defer_js deactivated.
