### ISSUE TITLE
PHP 7 

### ISSUE THREAD

**Issue by Juergen-Vollmer** [samuelet/indexmenu#221]
Hi,

I'm using dokuwiki "Hogfather" and "subjectindex" (2014-05-04) together with php 7.2.5 and get the following error:

 PHP Warning: Declaration of SI_EntryVerse::match($text) should be compatible with SI_Entry::match() in ...../dokuwiki/lib/plugins/subjectindex/plugins/EntryVerse.php on line 0

In order to fix that I have to change in file dokuwiki/lib/plugins/subjectindex/inc/matcher.php the follpwing line:

   old:
     function match() {
   new
  function match($text) {

Jürgen

**Comment by samuelet** [comment]
This is the indexmenu plugin, i think you should open the issue on subjectindex plugin page:
https://github.com/MrBertie/subjectindex/issues
