### ISSUE TITLE
ReferenceError: dTree is not defined

### ISSUE THREAD

**Issue by vonv** [samuelet/indexmenu#223]
Hi,

Dokuciki: Release rc2-2020-06-01 "Hogfather" RC2

When a namespace has a home page, in sidebar, the sub pages of the namespace not expanding.

And got this error in the browser console (FF):

`ReferenceError: dTree is not definedstart:102:41`

**Comment by samuelstj** [comment]
Same here on chrome.

Uncaught ReferenceError: dTree is not defined
    at doku.php?id=docs:cmb:start:173

**Comment by cdkeyleo** [comment]
Same problem here, dokuwiki was upgraded to _Release rc-2020-06-09 "Hogfather" RC3_
```
ReferenceError: dTree is not defined                            doku.php:110:41
    <anonymous> http://localhost:8885/doku.php?id=start:110
ReferenceError: dTree is not defined                             doku.php:528:41
    <anonymous> http://localhost:8885/doku.php?id=start:528
```

**Comment by syyongx** [comment]
> Thank. What do i have to do exactly ?
> 
> Put something like $conf['defer_js'] = 'false'; in my local.php ?

Right: $conf['defer_js'] = false;

**Comment by Klap-in** [comment]
An message for the users is added, to find the workaround for this issue. https://github.com/samuelet/indexmenu/commit/481a3cf8ef5cd438582902b1901edda0b7491b30

Long term fix is arriving via: https://github.com/samuelet/indexmenu/issues/230
