### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by rgleason** [samuelet/indexmenu#227]
We have been using indexmenu for many years. I was apprehensive about upgrade of Dokuwiki to HogFather and our upgrade [OpenCPN Dokuwiki (4 Books)](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual)   was very seamless, witn no problems from indexmenu or our other plugins..

Thank you!

[The Opencpn Team](https://opencpn.org/)

(You may close this thank you.)

**Comment by Klap-in** [comment]
Thanks!!!
(btw, there is still a big update needed for the javascript code of this plugin. So there are still some challenges to solve there.. let's see how we can do that smooth)

**Comment by samuelet** [comment]
Thanks.
I close this issue, the challenge continues here: #230
