### ISSUE TITLE
DocuWiki Hogfather Version Compatibility?

### ISSUE THREAD

**Issue by GameDoc-MS** [samuelet/indexmenu#232]
Is this plugin compatible with the DocuWiki Hogfather Version?
thx

**Comment by Klap-in** [comment]
The Hogfather release of DokuWiki does now default used deferred loading of javascript.
The indexmenu plugin does has inline javascript, which is not compatible with deferred loading of javascript.
So to let it work, you have to use the feature flag 'defer_js' in the Configuration Manager.

If you use this feature flag, according to my information the indexmenu plugin should just work. If you see other issues, please report here.

**Comment by rgleason** [comment]
That fixed it!
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
Thank you
