### ISSUE TITLE
Statement on Hogfather compatibility

### ISSUE THREAD

**Issue by Michaelsy** [samuelet/indexmenu#234]
On the plugin page it is stated that Indexmenu is not compatible with Hogfather. Is this information intended?

\- Michael Sy.

**Comment by rgleason** [comment]
We are using indexmenu with Hogfather ,  https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
(However we can no longer use the bootstrap3 template with Hogfather.)

**Comment by Klap-in** [comment]
I think if you disable defer_js, this plugin is compatible.
This person who changed this, has not filed an issue report so far know...

**Comment by rgleason** [comment]
Yes, I failed to mention that disabling defer_js is what really solved all problems. Before we were getting just partial indexes that could not be used for site navigation.

**Comment by Klap-in** [comment]
Work in progress: https://github.com/samuelet/indexmenu/issues/230 

disabling defer_js is added as note.

If the javascript-update is finalized, the compatibility will surely be updated. If disabling defer_js is a good enough workaround for others, it is fine for me to set the compatibility status to 'yes'.
