### ISSUE TITLE
Page not displayed if parent namespace is also a page

### ISSUE THREAD

**Issue by pkuehne** [samuelet/indexmenu#238]
I have a namespace, which is also a page underneath which I have another page. This is to allow hierarchical nesting of pages.

So navigating to `domain.com/foo` shows a normal page with text and images.
Navigating to `domain.com/foo/bar` shows another page with text and images.
If I place the `indexmenu` macros inside the `foo` page, like so:

`{{indexmenu>.|js}}` I only see the foo page (styled as a namespace), but not the `bar` subpage. It does appear if I use the `nons` option, but then the hierarchy is lost.

**Comment by Klap-in** [comment]
The setting 'plugin»indexmenu»headpage' has enabled `:same`-option. Therefore, the `foo` page is recognized as headpage, and used as link of the `foo`-namespace. 

If I use your syntax example, then I get this. So there is a `bar`-page in the `foo`-namespace. And the `foo`-namespace item is clickable to the `foo`-page.
![foo-bar-example](https://user-images.githubusercontent.com/183250/125167597-accc8180-e1a1-11eb-9ca2-4ba26627bb7d.png)

If I use `{{indexmenu>.|js nopg}}`, then the pages (e.g. `bar` in your case) are hidden, and I get only the namespaces, with clickable links to their headpage (in your case a link to `foo`-page).

Could it be that in the Config Manager the 'plugin»indexmenu»defaultoptions', already `nopg` is added to settings?

**Comment by Klap-in** [comment]
No response, therefore closing.
