### ISSUE TITLE
Subpage isn't showing into the menu if has same namespace name than parent namespace

### ISSUE THREAD

**Issue by eduardomozart** [samuelet/indexmenu#240]
If I create a page into the ``:ad:gpo:user:adm:desktop:desktop``, the IndexMenu shows only ``:ad:gpo:user:adm:desktop`` into the sidebar, the subnamespace below ``desktop`` (that's also called ``desktop``) isn't shown. 

![2021-04-12 09_14_21-teste](https://user-images.githubusercontent.com/2974895/114392905-c8f35f00-9b6f-11eb-83e7-ecdb3dd6ac76.png)

But if I rename the last ``desktop`` for something else (e.g ``:ad:gpo:user:adm:desktop:somethingelse``), it's shown normally.

![2021-04-12 09_15_02-teste](https://user-images.githubusercontent.com/2974895/114392915-cbee4f80-9b6f-11eb-954d-0fa8adc090ea.png)

It doesn't seem to be related to the template used because it happens even with DokuWiki default template and third party templates.

Some debug info:

DokuWiki version: Release 2020-07-29 "Hogfather"
Template: Vector

Code that I'm using into ``:wiki:sidebar`` namespace:

```
{{indexmenu>..:#1|js#doku2 navbar nsort nocookie}}
```

Please let me know if anymore information are needed.

**Comment by samuelet** [comment]
This is the right behaviour , when useheading and hide_headpage are enabled .Could you check them? :
https://www.dokuwiki.org/plugin:indexmenu#namespaces_title_and_link_headpages

**Comment by eduardomozart** [comment]
But it shouldn't be a default behavior, because sub pages isn't shown and for a user that do not know it can happen may think that it's sub page doesnt exist. The plugin should be able to list sub pages that has the same namespace name than its parent. E.g. :ad:gpo:user:adm:desktop:desktop should be shown into IndexMenu tree, but only :ad:gpo:user:adm:desktop is shown.

**Comment by samuelet** [comment]
Could you post screenshots of the missing namespace and of the working tree with renamed ns?
Is the Aclcache disabled?

**Comment by eduardomozart** [comment]
Hello, the ``aclcache`` option is set to "Groups", as I use groups to set ACLs to external users that access the Wiki.
I updated the first comment to include screenshots of the issue.

**Comment by Klap-in** [comment]
What is set for the setting 'plugin»indexmenu»headpage' in your wiki?

Could you try to disable `:inside:`? That option tells that an page inside a namespace with the same name as the namespace should be seen as a headpage.

**Comment by eduardomozart** [comment]
The setting 'plugin»indexmenu»headpage' is set to ``:start:``, ``:same:`` and ``:inside:``.
I disabled the ``:inside:`` checkbox and it shows the child page as expected. Thank you!
