### ISSUE TITLE
Update to PHP8 makes indexmenu fail

### ISSUE THREAD

**Issue by chrisisbd** [samuelet/indexmenu#247]
I have just updated one of my systems to xubuntu 21.10 which, among other things, changes PHP to version 8.

I'm now getting lots of errors from the indexmenu plugin:-

[Tue Nov 02 16:11:14.617205 2021] [php:warn] [pid 35851] [client 192.168.1.3:41980] PHP Warning:  Undefined array key "userinfo" in /home/chris/wiki/lib/plugins/indexmenu/action.php on line 54
[Tue Nov 02 16:11:14.625035 2021] [php:warn] [pid 35851] [client 192.168.1.3:41980] PHP Warning:  Undefined array key "stylesheets" in /home/chris/wiki/inc/StyleUtils.php on line 102
[Tue Nov 02 16:11:14.626834 2021] [php:warn] [pid 35851] [client 192.168.1.3:41980] PHP Warning:  Undefined array key "userinfo" in /home/chris/wiki/lib/plugins/indexmenu/action.php on line 86
[Tue Nov 02 16:11:14.626850 2021] [php:warn] [pid 35851] [client 192.168.1.3:41980] PHP Warning:  Trying to access array offset on value of type null in /home/chris/wiki/lib/plugins/indexmenu/action.php on line 86
[Tue Nov 02 16:11:14.629006 2021] [php:warn] [pid 35851] [client 192.168.1.3:41980] PHP Warning:  Undefined array key "userinfo" in /home/chris/wiki/lib/plugins/indexmenu/action.php on line 86
[Tue Nov 02 16:11:14.629027 2021] [php:warn] [pid 35851] [client 192.168.1.3:41980] PHP Warning:  Trying to access array offset on value of type null in /home/chris/wiki/lib/plugins/indexmenu/action.php on line 86

**Comment by Klap-in** [comment]
Fixed by #134
(note that the second warning is not related to indexmenu)
