### ISSUE TITLE
Configuration Setting: defer_js -> active -> indexmenu does not show up

### ISSUE THREAD

**Issue by cweikl** [samuelet/indexmenu#249]
Having upgraded from Greebo with a working indexmenu to Hogfather, the indexmenu does not show up, until I deactivate the configuration setting defer_js.

Having deactivated defer_js other plugins like the the EditTable plugin do not show up e.g. their buttons within the editor.
Is there a workaround or bugfix?
Thanks.

**Comment by Klap-in** [comment]
No, not yet. I’m working on an update of the Indexmenu plugin, which replaces the old tree rendering completely. See #230
