### ISSUE TITLE
Limitation in depth for indexation

### ISSUE THREAD

**Issue by jeffchulg** [samuelet/indexmenu#251]
I created a page like this : 

`dokuwiki:team:application1:day2day:field1:subfield1:start`

in this page  : `{{indexmenu>.:#3|navbar js max#3#2 tsort msort}}`

I created another page 

`dokuwiki:team:application1:day2day:field1:subfield1:test`

Test page is not shown on start page, neither anywhere.

I think there is a depth limit set to 5 somewhere....

**Comment by Klap-in** [comment]
For me page `test` appears in the indexmenu. Also in other indexmenu's that just show my entire wiki. Did you try to add more pages than `test`? 

I'm using the latest version of the plugin, which includes some big internal rewrites, not sure if it makes a difference. But if you update to the latest version, you check that as well.

Can you with the latest version, also check if `{{indexmenu>.:#3|navbar js max#3#2 tsort msort treenew}}` shows different? (the appearance will change)

Why do you use `msort`? Are there other non default settings which I might consider for trying to reproduce your situation?

**Comment by Klap-in** [comment]
Please reopen, if still an issue with info.
