### ISSUE TITLE
indexmenu will not show all folders (ns)

### ISSUE THREAD

**Issue by maxens1** [samuelet/indexmenu#255]
Why not all folders show in the menu?

I use `{{indexmenu>en:app:#2 |js#drktheme nopg hsort}}`

folders are

```
en->App 
    ->  Home
    ->  General
    ->  Specifics
    ->  Reference
en->FAQ
```

Menu will only show first two folders

App
->     Home 
->    General
FAQ

If I change #2 with #3 it does show all folders but also the subfolders.
Any suggestions?

**Comment by Klap-in** [comment]
If have no idea yet.
Does the folders ‘Specifics’ and ‘Reference’ also have pages or other folders in them? They are not empty?
Does it behave differently without the setting ‘hsort’?
What is your current DokuWiki config setting for [useheading](https://www.dokuwiki.org/config:useheading) ?

**Comment by Klap-in** [comment]
Please reopen with additional information.
