### ISSUE TITLE
deprecated Function in IGOR

### ISSUE THREAD

**Issue by LMS235** [samuelet/indexmenu#256]
After update to IGOR:

JSON::encode() is deprecated. It was called from syntax_plugin_indexmenu_indexmenu::_jsnodes() in <xxx>/wiki/lib/plugins/indexmenu/syntax/indexmenu.php:549 json_encode should be used instead!

**Comment by Klap-in** [comment]
To be sure, that is with the latest version of the Indexmenu?

**Comment by Klap-in** [comment]
Ah, I found it already. I will change it, probably this evening.

**Comment by Klap-in** [comment]
Fixed in #e6134db4b6cabc1904473be056d4b50c30566bf2

**Comment by ParoTheParrot** [comment]
@Klap-in : by closing this issue, is indexmenu compatible to Igor?
In this case, please update https://www.dokuwiki.org/plugin:indexmenu. 
TIA, Paro!

**Comment by Klap-in** [comment]
In Hogfather and Igor you have to set an feature flag: https://www.dokuwiki.org/plugin:indexmenu

To improve that I’m implementing https://github.com/samuelet/indexmenu/issues/230
That is a bit slow process. 
In general php7 will work fine, I saw already some details related to php8 which could maybe cause issues.
