### ISSUE TITLE
Menu Display Settings

### ISSUE THREAD

**Issue by lmalevich** [samuelet/indexmenu#265]
Are there settings to:
1) Remove the drop-down menu (see screenshot)
![image](https://github.com/samuelet/indexmenu/assets/74589127/d31853e8-ee02-484f-ac8a-fedea99a7bbc)
2) All namespaces are collapsed by default
3) Show currently opened page in menu (for example in bold)
4) Set up right-click menu (see screenshot)
![image](https://github.com/samuelet/indexmenu/assets/74589127/ed1a8f51-b36f-473e-8745-f81455b5874b)

Would appreciate any help!

**Comment by Klap-in** [comment]
1.  Disable default the Table of Content (toc) with: `notoc` in https://www.dokuwiki.org/plugin:indexmenu#default_options
2. What is your question?
3. What is your question?
4. Enabling menu with `menu`, or disable with `nomenu`, can be added to the default options as well.

**Comment by lmalevich** [comment]
> 2. What is your question?

This question has been solved. I just wanted to see not the entire menu, but only the namespace, no pages :)


> 3. What is your question?

I want the menu to show which page is currently open. For example, as on your site, the open page is highlighted in yellow in the menu (see screenshot). Only I would not like to highlight in color, but in bold.
![image](https://github.com/samuelet/indexmenu/assets/74589127/c1ad4d24-b163-4752-aefd-8464944d1bcb)
