### ISSUE TITLE
PHP 8.1 error - Undefined array key 1 on line 697

### ISSUE THREAD

**Issue by ml17950** [samuelet/indexmenu#267]
Hi.

## Problem
I'm using indexmenu (version 2022-08-01) in the sidebar with following options:
```
{{indexmenu>:#1|navbar nocookie notoc nomenu tsort nsort max#2 skipfile+/(footer|navigation)/}}
```
and get on some pages following error/warning:
```
Warning: Undefined array key 1 in .......\dokuwiki\lib\plugins\indexmenu\syntax\indexmenu.php on line 697
```

## Possible Solution
replace line 697 with:
```
if(isset($nss[$a][1]) && ($nss[$a][1] == -1 || substr_count($match[1], ":") < $nss[$a][1])) {
````

## Environment
Windows / Apache 2.4.56 / PHP 8.1.17 / Dokuwiki 2023-04-04a "Jack Jackrum" and 2023-06-12 "snapshot"

**Comment by Klap-in** [comment]
If using the `navbar` it did not set a level, fixed by explicitly setting the number of levels that should open to 1. Thanks for reporting.
