### ISSUE TITLE
Customize line breaks in the sidebar

### ISSUE THREAD

**Issue by lmalevich** [samuelet/indexmenu#268]
I want the menu to display without horizontal scrolling and with line breaks. I found how to disable scrolling (noscroll command), but I can't find information on how to enable line breaks so that the menu items don't extend beyond the edges of the sidebar, please help!

**Comment by Klap-in** [comment]
There is not such option built in. Might be there is an possibility to do it with css, but I did not look if that is a realistic suggestion.

**Comment by Klap-in** [comment]
I have added a new javascript tree, however it layout is a bit different.
You can enable it by adding `treenew` to the options. Does this improve your situation?

**Comment by Klap-in** [comment]
Because my understanding is that the different layout of the new `treenew` tree will improve the situation, I'm closing this issue.
