### ISSUE TITLE
Working OK, Several warnings on log

### ISSUE THREAD

**Issue by dragonauta** [samuelet/indexmenu#272]
Hi! The plugin works as expected. But looking in log for another plugin,  I went to the Dokuwiki's log and wanted to inform I found these:

> 2023-11-09 19:07:41E_WARNING: Undefined array key "nss"/var/www/html/doku/lib/plugins/indexmenu/action.php(307)
>     #0 /var/www/html/doku/lib/plugins/indexmenu/action.php(307): dokuwiki\ErrorHandler::errorHandler()
>     #1 /var/www/html/doku/lib/plugins/indexmenu/action.php(170): action_plugin_indexmenu->print_index()
>     #2 /var/www/html/doku/inc/Extension/EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
>     #3 /var/www/html/doku/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
>     #4 /var/www/html/doku/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
>     #5 /var/www/html/doku/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
>     #6 {main}
> 2023-11-09 19:07:41E_WARNING: Undefined array key "sort"/var/www/html/doku/lib/plugins/indexmenu/action.php(308)
>     #0 /var/www/html/doku/lib/plugins/indexmenu/action.php(308): dokuwiki\ErrorHandler::errorHandler()
>     #1 /var/www/html/doku/lib/plugins/indexmenu/action.php(170): action_plugin_indexmenu->print_index()
>     #2 /var/www/html/doku/inc/Extension/EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
>     #3 /var/www/html/doku/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
>     #4 /var/www/html/doku/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
>     #5 /var/www/html/doku/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
>     #6 {main}
> 2023-11-09 19:07:41E_WARNING: Undefined array key "msort"/var/www/html/doku/lib/plugins/indexmenu/action.php(309)
>     #0 /var/www/html/doku/lib/plugins/indexmenu/action.php(309): dokuwiki\ErrorHandler::errorHandler()
>     #1 /var/www/html/doku/lib/plugins/indexmenu/action.php(170): action_plugin_indexmenu->print_index()
>     #2 /var/www/html/doku/inc/Extension/EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
>     #3 /var/www/html/doku/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
>     #4 /var/www/html/doku/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
>     #5 /var/www/html/doku/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
>     #6 {main}
> 2023-11-09 19:07:41E_WARNING: Undefined array key "rsort"/var/www/html/doku/lib/plugins/indexmenu/action.php(310)
>     #0 /var/www/html/doku/lib/plugins/indexmenu/action.php(310): dokuwiki\ErrorHandler::errorHandler()
>     #1 /var/www/html/doku/lib/plugins/indexmenu/action.php(170): action_plugin_indexmenu->print_index()
>     #2 /var/www/html/doku/inc/Extension/EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
>     #3 /var/www/html/doku/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
>     #4 /var/www/html/doku/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
>     #5 /var/www/html/doku/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
>     #6 {main}
> 2023-11-09 19:07:41E_WARNING: Undefined array key "nsort"/var/www/html/doku/lib/plugins/indexmenu/action.php(311)
>     #0 /var/www/html/doku/lib/plugins/indexmenu/action.php(311): dokuwiki\ErrorHandler::errorHandler()
>     #1 /var/www/html/doku/lib/plugins/indexmenu/action.php(170): action_plugin_indexmenu->print_index()
>     #2 /var/www/html/doku/inc/Extension/EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
>     #3 /var/www/html/doku/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
>     #4 /var/www/html/doku/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
>     #5 /var/www/html/doku/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
>     #6 {main}
> 2023-11-09 19:07:41E_WARNING: Undefined array key "hsort"/var/www/html/doku/lib/plugins/indexmenu/action.php(312)
>     #0 /var/www/html/doku/lib/plugins/indexmenu/action.php(312): dokuwiki\ErrorHandler::errorHandler()
>     #1 /var/www/html/doku/lib/plugins/indexmenu/action.php(170): action_plugin_indexmenu->print_index()
>     #2 /var/www/html/doku/inc/Extension/EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
>     #3 /var/www/html/doku/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
>     #4 /var/www/html/doku/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
>     #5 /var/www/html/doku/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
>     #6 {main}
> 2023-11-09 19:07:41E_WARNING: Undefined array key "skipfile"/var/www/html/doku/lib/plugins/indexmenu/action.php(315)
>     #0 /var/www/html/doku/lib/plugins/indexmenu/action.php(315): dokuwiki\ErrorHandler::errorHandler()
>     #1 /var/www/html/doku/lib/plugins/indexmenu/action.php(170): action_plugin_indexmenu->print_index()
>     #2 /var/www/html/doku/inc/Extension/EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
>     #3 /var/www/html/doku/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
>     #4 /var/www/html/doku/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
>     #5 /var/www/html/doku/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
>     #6 {main}
> 2023-11-09 19:07:41E_WARNING: Uninitialized string offset 1/var/www/html/doku/lib/plugins/indexmenu/action.php(319)
>     #0 /var/www/html/doku/lib/plugins/indexmenu/action.php(319): dokuwiki\ErrorHandler::errorHandler()
>     #1 /var/www/html/doku/lib/plugins/indexmenu/action.php(170): action_plugin_indexmenu->print_index()
>     #2 /var/www/html/doku/inc/Extension/EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
>     #3 /var/www/html/doku/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
>     #4 /var/www/html/doku/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
>     #5 /var/www/html/doku/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
>     #6 {main}
> 2023-11-09 19:07:41E_WARNING: Undefined array key "skipns"/var/www/html/doku/lib/plugins/indexmenu/action.php(324)
>     #0 /var/www/html/doku/lib/plugins/indexmenu/action.php(324): dokuwiki\ErrorHandler::errorHandler()
>     #1 /var/www/html/doku/lib/plugins/indexmenu/action.php(170): action_plugin_indexmenu->print_index()
>     #2 /var/www/html/doku/inc/Extension/EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
>     #3 /var/www/html/doku/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
>     #4 /var/www/html/doku/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
>     #5 /var/www/html/doku/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
>     #6 {main}
> 2023-11-09 19:07:41E_WARNING: Uninitialized string offset 1/var/www/html/doku/lib/plugins/indexmenu/action.php(328)
>     #0 /var/www/html/doku/lib/plugins/indexmenu/action.php(328): dokuwiki\ErrorHandler::errorHandler()
>     #1 /var/www/html/doku/lib/plugins/indexmenu/action.php(170): action_plugin_indexmenu->print_index()
>     #2 /var/www/html/doku/inc/Extension/EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
>     #3 /var/www/html/doku/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
>     #4 /var/www/html/doku/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
>     #5 /var/www/html/doku/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
>     #6 {main}
> 2023-11-09 19:07:41E_WARNING: Undefined array key "nons"/var/www/html/doku/lib/plugins/indexmenu/action.php(336)
>     #0 /var/www/html/doku/lib/plugins/indexmenu/action.php(336): dokuwiki\ErrorHandler::errorHandler()
>     #1 /var/www/html/doku/lib/plugins/indexmenu/action.php(170): action_plugin_indexmenu->print_index()
>     #2 /var/www/html/doku/inc/Extension/EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
>     #3 /var/www/html/doku/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
>     #4 /var/www/html/doku/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
>     #5 /var/www/html/doku/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
>     #6 {main}
> 2023-11-09 19:07:41E_WARNING: Undefined array key "nopg"/var/www/html/doku/lib/plugins/indexmenu/action.php(340)
>     #0 /var/www/html/doku/lib/plugins/indexmenu/action.php(340): dokuwiki\ErrorHandler::errorHandler()
>     #1 /var/www/html/doku/lib/plugins/indexmenu/action.php(170): action_plugin_indexmenu->print_index()
>     #2 /var/www/html/doku/inc/Extension/EventHandler.php(80): action_plugin_indexmenu->_ajax_call()
>     #3 /var/www/html/doku/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
>     #4 /var/www/html/doku/inc/Ajax.php(27): dokuwiki\Extension\Event->advise_before()
>     #5 /var/www/html/doku/lib/exe/ajax.php(22): dokuwiki\Ajax->__construct()
>     #6 {main}

My system is:
DokuWiki 2023-04-04a "Jack Jackrum"
Debian Bookworm 12.1
PHP 8.2.7
Apache2 2.4.57

**Comment by Klap-in** [comment]
Can you please update to the latest version, and confirm if these warnings are solved?

**Comment by dragonauta** [comment]
Solved! No more warnings. At least for me, no more log messages.
