### ISSUE TITLE
E_WARNING: Undefined array key "userinfo"

### ISSUE THREAD

**Issue by nerun** [samuelet/indexmenu#278]
This is the same issue as #247, closed. Apparently it was fixed by the already merged PR #134. But the changes made by that PR were `partially` undone. Now i receive TONS of warnings, ALL them related to this single issue:

```
******
[Log file too large. Previous lines skipped!]

E_WARNING: Undefined array key "userinfo"
.../lib/plugins/indexmenu/action.php(71)
```

I will submit a PR to change action.php line 71 from:
```php
$JSINFO['isauth'] = (int) $INFO['userinfo'];
```
Back to the same as PR #134:
```php
$JSINFO['isauth'] = isset($INFO['userinfo']) ? (int) $INFO['userinfo'] : 0;
```

**Comment by Klap-in** [comment]
Thanks for reporting again. Why does `(int)$INFO['userinfo'] ?? 0;` not work, probably because casting to (int) is performed before the null coalescing operator `??`?

**Comment by Klap-in** [comment]
Merged, thanks!
