### ISSUE TITLE
JavaScript Error: "ReferenceError: Can't find variable: IndexmenuUtils"

### ISSUE THREAD

**Issue by choules** [samuelet/indexmenu#282]
We have just upgraded our DokuWiki installation and the indexmenu plugin to the most recent version. After the update we have encountered an issue where the folder images are not shown any more in Safari. This is due to a JavaScript error, which also leads to not being able to click on the menu items any more:

```
[Error] ReferenceError: Can't find variable: IndexmenuUtils
	dTree (js.php:1:124984)
	Global Code (home:192)
```

`js.php:1:124984` is somewhere 

Other browsers (Chrome, Firefox) are not affected by this issue. Of course we have ensured to delete all caches.

Enabling the defer_js option of DokuWiki does not fix this issue.

We have then tried to switch over to the `treenew`, but this leads to another issue...

**Comment by choules** [comment]
Manually downloading and installing the release v2023-12-14 fixes the issue for me. But DokuWiki still suggests that the plugin needs an update. The displayed download url is `https://github.com/samuelet/indexmenu/archive/master.zip` which does not match the latest release but the master branch. So probably my issue is related to the current commit ddf71e1d771fef14b2f56ae66de1f173fad1134b

If that's the case you should consider keeping the master branch clean and on the same level as the latest release.

**Comment by choules** [comment]
The release v2023-12-14 contains an outdated plugin.info.txt, which was updated in 527a9ee5d22275a6eb2b8e55689c5a2327f4359f. This probably leads to DokuWiki thinking that the installed plugin is not up to date. Perhaps you should update the release accordingly.

Thanks for all you work!

**Comment by Klap-in** [comment]
I'm not sure how this happens. I did a first attempt to fix. Could you try to update to the latest version?

**Comment by choules** [comment]
Thanks for your quick fix, it seems to do the trick. No problems after updating using the DokuWiki interface.
