### ISSUE TITLE
treenew: DokuWiki basedir option is not respected

### ISSUE THREAD

**Issue by choules** [samuelet/indexmenu#283]
Looking for a workaround on issue #282, we have tried to switch over to the `newtree` option. But with this option we did not see any images. Looking at the browser console we could see that the referenced images were not found, because the given URL was looking for files at the root level of our webserver.

We have installed DokuWiki at `https://myserver/dokuwiki`, so the image would be found at `https://myserver/dokuwiki/lib/plugins/indexmenu/scripts/fancytree/skin-win7/loading.gif` (which actually loads fine), but the CSS file is referencing only `https://myserver/lib/plugins/indexmenu/scripts/fancytree/skin-win7/loading.gif`

Checking the source code I have not found a reference to `DOKU_BASE` anywhere in the `treenew` code.

**Comment by choules** [comment]
See my comment [on #282](https://github.com/samuelet/indexmenu/issues/282#issuecomment-1876995185), the issue is not present any more after reverting to a manually downloaded v2023-12-14 release, as well.

**Comment by Klap-in** [comment]
Thanks for reporting! in javascript had already implemented support for basedir, but I did not think of the css. If you found more of them please tell, as my test setup has no basedir set at the moment, so difficult to test.

**Comment by Klap-in** [comment]
Thanks for the feedback.
