### ISSUE TITLE
Collapse all except path to current node

### ISSUE THREAD

**Issue by cepm-nate** [samuelet/indexmenu#288]
Is there a mode to default "collapse all except path to current node"? I'd expect this to be somewhat useful with the navbar setting. I've read through the options, did I miss it?

**Comment by Klap-in** [comment]
You like to only expand the current node?

```
{{indexmenu>:#1|navbar}}
```
Adding #number set the number of levels that should expanded on load. So `#1` loads one level from the requested namespace.

**Comment by cepm-nate** [comment]
Ah, I misread the # usage, and didn't experiment enough. 

I also cloned the repo, and if I get time, will look into a way (as an option) to bring in a TOC (customizeable levels deep) into the SEARCH function so it's also in the tree.

Thanks for all your work on this!
