### ISSUE TITLE
Indexmenu requires Admin>Configuration>Save every time Page Titles are edited

### ISSUE THREAD

**Issue by rgleason** [samuelet/indexmenu#297]
See  closed https://github.com/samuelet/indexmenu/issues/296
Resolution of the this issue was to save the configuration, which updates the sidebar index menu.
Now, every time I edit a title in a page, I have to go to configuration > Save.

It used to be more seamless, with the sidebar updating when changes are made.
Can this be fixed I hope?

LATER: Also see https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:edit_user_manual:indexmenu_plugin#navigation_and_table_of_contents

for info on how indexmenu is set up.

**Comment by Klap-in** [comment]
Ah, this actually a continuation of the other issue ;-) was fine for me to reopen.

Your testing with resaving the Configuration Manager shows it is a caching issue. This will probably take some effort for me to test were that happens, it depends often on details, and see how I can let it expire at the right moment. So I hope you could be patience with me. :-)

**Comment by Klap-in** [comment]
In general I expect that the Kaos upgrade will not affect this different, because I use that already on my test machine. So I would an upgrade not let depend on this issue.

**Comment by rgleason** [comment]
Tbanks Klap-in. There are certainly worse issues at times. I can wait, other editors may be puzzled but Ill try to let them know.

**Comment by Klap-in** [comment]
I moved back to the other thread as it contains more info about the caching issue.

Btw, offtopic remark: I see a remark about sorting namespaces and pages, you know the options `nsort` and `group` exists? Not sure if that is what you meant, but if so, these are interesting to test?

**Comment by hupb** [comment]
Don't know if it's helpful, but after removing the word  _hasindexmenu_ in _action.php/line 95_ **p_get_metadata($ID, 'indexmenu hasindexmenu')** i get the usual behavior ...
