### ISSUE TITLE
Tree collapse after click on any link

### ISSUE THREAD

**Issue by DrKlipper** [samuelet/indexmenu#298]
Hi !
Just updated to the latest version and now my tree has a very strange behavior. 
Whenever I click on a namespace or page link, the complete tree collapse. 
This is really annoying because you have always click through the tree to get to another page. 

Example: 
![grafik](https://github.com/samuelet/indexmenu/assets/119651689/11aa8474-3b3c-4698-b6d2-5f3a1e459198)
When I click on any link - lets say KiCAD - the tree collapses: 
![grafik](https://github.com/samuelet/indexmenu/assets/119651689/164aa93e-e0de-4e1c-b913-a188a131b6ed)

The page (in this case KiCAD) will be opened. But the tree collapses. 

This is my sidebar notation: 
`{{indexmenu>.#1|js#bj_ubuntu.png noscroll skipfile=/sidebar|temp|dominik_schmidt|impressum/}} `

**Comment by Klap-in** [comment]
Do you see any message in the Console of your browser?
Does it make a difference if you resave the Configuration Manager (this expires all caches)?

**Comment by DrKlipper** [comment]
Thx for pointing to the Console. 
I saw some cookie errors which came from the non-existent HTTPS connection. 
After enabling HTTPS all is fine now. THX

**Comment by DrKlipper** [comment]
Fixed

**Comment by m199841** [comment]
Hey, I seemingly have the same problem. I am not really sure what you did @DrKlipper - do you care to elaborate?

It seems that no cookies about the state of the tree is saved (even though it should be enabled).
The exact same sidebar notation gives me the correct behavior (saves the state of the tree) when I open my DokuWiki from the localhost:8999 (I changed the port) - which means it is probably related to some security setting but changing the configuration file (securecookie ??) did not change this.

**Comment by m199841** [comment]
Quick update on this. I had to remove the secure tag for setting cookies in the indexmenu.js file. 
I did not get any errors or issues in the console but since my connection to an (internal) DokuWiki is not secure I suspect it cannot set secure cookies when the flag is enabled. 
This is no issue when connecting to localhost because there one can always (?) set secure cookies.
