### ISSUE TITLE
E_WARNING: Trying to access array offset on value of type null 

### ISSUE THREAD

**Issue by macin** [samuelet/indexmenu#305]
Hi, I am getting a lot of errors like this

`2024-02-28 17:42:39
E_WARNING: Trying to access array offset on value of type null
/var/www/html/lib/plugins/indexmenu/syntax/indexmenu.php(842)
#0 /var/www/html/lib/plugins/indexmenu/syntax/indexmenu.php(842): dokuwiki\ErrorHandler::errorHandler(2, '...', '...', 842)
#1 /var/www/html/inc/html.php(500): syntax_plugin_indexmenu_indexmenu->formatIndexmenuItem(Array)
#2 /var/www/html/lib/plugins/indexmenu/syntax/indexmenu.php(544): html_buildlist(Array, '...', Array, Array)
#3 /var/www/html/lib/plugins/indexmenu/syntax/indexmenu.php(531): syntax_plugin_indexmenu_indexmenu->buildNoJSTree(Array, '...', '...')
#4 /var/www/html/lib/plugins/indexmenu/syntax/indexmenu.php(466): syntax_plugin_indexmenu_indexmenu->buildHtmlIndexmenu('...', Array, Array, Array, 1)
#5 /var/www/html/lib/plugins/text/renderer.php(45): syntax_plugin_indexmenu_indexmenu->render('...', Object(renderer_plugin_text), Array)
#6 /var/www/html/inc/parserutils.php(691): renderer_plugin_text->plugin('...', Array, 5, '...')
#7 /var/www/html/inc/parserutils.php(158): p_render('...', Array, NULL)
#8 /var/www/html/lib/plugins/searchtext/action.php(34): p_cached_output('...', '...')
#9 /var/www/html/inc/Extension/EventHandler.php(80): action_plugin_searchtext->_getSearch(Object(dokuwiki\Extension\Event), NULL)
#10 /var/www/html/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), '...')
#11 /var/www/html/inc/indexer.php(189): dokuwiki\Extension\Event->advise_before()
#12 /var/www/html/inc/TaskRunner.php(206): idx_addPage('...', true)
#13 /var/www/html/inc/TaskRunner.php(52): dokuwiki\TaskRunner->runIndexer()
#14 /var/www/html/lib/exe/taskrunner.php(20): dokuwiki\TaskRunner->run()
#15 {main}
`
What could be the reason. Using the old indexmenu syntax.

**Comment by macin** [comment]
Ok, seems like the issue was with dokuwiki itself. There is a newer version (kaps 2024-02-06a) which fixes the problem

**Comment by Klap-in** [comment]
Ok, perfect. Otherwise you may reopen it again.
