### ISSUE TITLE
Tool in Admin Area missing

### ISSUE THREAD

**Issue by LMS235** [samuelet/indexmenu#308]
Hello,

in older Installations (also in updated ones) there is a Indexmenu-Tool in the admin area:

![image](https://github.com/samuelet/indexmenu/assets/8693550/a9c235b0-c8bf-454f-ba80-03be1118dfb8)

![image](https://github.com/samuelet/indexmenu/assets/8693550/cdce8761-272f-4bb6-a60b-885d4e03d97a)

will it be available again? is it needed (I used to install other icons with it)? Or will it be removed with an update?

**Comment by Klap-in** [comment]
All themes which were available via this admin tool are now already included with the plugin, so direct available. We recommend to submit proposals for new theme via GitHub. Or email if someone has no account on GitHub.

Also a new JavaScript tree is introduced. For this version the use of other skins/themes will be documented better at a later moment.

**Comment by LMS235** [comment]
ok, how can I remove it cleanly?

**Comment by Klap-in** [comment]
admin.php can just be removed. However, at the moment we do not yet use a deleted.files file, it will be added at a later point. That file will instruct the Extension Manager after an update to clean up the listed files.

**Comment by LMS235** [comment]
ok - bug closed ;)
