### ISSUE TITLE
namespaces don't hide if further sub-namespaces exist

### ISSUE THREAD

**Issue by eberproducts** [samuelet/indexmenu#62]
Hi, 
i have an ACL controlled dokuwiki and i use the latest version of indexmenu. 

My problem is, that if you are NOT logged in, all namespaces containing further subnamespaces are still shown on the Menu. All other namespaces are hide. 

So what can i do to hide the namespaces containing subnamespaces as well for not logged in User?

**Comment by Klap-in** [comment]
Since #102 is implemented, removing of empty dirs is performed for (only) the sort options:
tsort, dsort, msort, nsort and hsort.
