### ISSUE TITLE
Indexmenu id conflict

### ISSUE THREAD

**Issue by chang-zhao** [samuelet/indexmenu#67]
I create fresh DokuWiki install (DokuWiki on a Stick), add indexmenu and create "sidebar" file:
{{indexmenu>:|js navbar nocookie id#random}}

Then going to sidebar file gives
Indexmenu id conflict
![indexmenu_bug_3a](https://f.cloud.github.com/assets/5161535/2460226/c786af2e-af67-11e3-9c33-cb4a5dd543bc.png)

**Comment by Michaelsy** [comment]
A workaround to get rid of the warning message, is to use the [Nosidebar plugin](https://www.dokuwiki.org/plugin:nosidebar)  to remove the sidebar on the sidebar page.
