### ISSUE TITLE
The red triangle of Content Preview in the tree is not shown in some cases

### ISSUE THREAD

**Issue by chang-zhao** [samuelet/indexmenu#69]
When the most lengthy string in the tree ends at the border of the panel, then there is no place for the red triangle to preview the page content. And, on the other hand, the scrolling arrow doesn't appear, because it thinks the width is enough.

![indexmenu_bug_5](https://f.cloud.github.com/assets/5161535/2481299/4c48eea0-b0d7-11e3-86bb-8f5619662821.png)

I think that the width of that red arrow should be added to the tree width when determining final tree width. Otherwise also it's very not convinient when the sidebar gets resized according to the tree width - every time the lengthest pagename can't be previewed for content.

**Comment by Klap-in** [comment]
In new version of Indexmenu the scrolling wil be removed, an probably also Table of Content button (the red triangel button) will be removed. Therefore, this request will be closed as well.
