### ISSUE TITLE
Country-specific characters are not sorted correctly

### ISSUE THREAD

**Issue by raba34** [samuelet/indexmenu#75]
Hello,
obviously country-specific characters are not sorted correctly. Ö (O umlaut) is ranked all the way back. It would be correct but sorting before P.
Ralph

**Comment by chang-zhao** [comment]
I have a strange bug: sometimes sorting is correct (pic. 1)
'{{indexmenu>#1 .#1|js#thread navbar context id#random msort tsort nsort}}'
![correct-order](https://cloud.githubusercontent.com/assets/5161535/6882515/76a625c8-d598-11e4-8b0f-29f7db93b50b.png)
Pic. 1. The correct order

but sometimes sorting is wrong (see letters  М Н О П appear before the rest) (pic. 2),
as if the locale would be wrong.
Reloading a page often makes incorrect sorting to become correct.
![incorrect-order](https://cloud.githubusercontent.com/assets/5161535/6882518/8550afd0-d598-11e4-8651-41a87b30097a.png)
Pic. 2. The incorrect order

Any advice?

**Comment by Klap-in** [comment]
Recent work in DokuWiki core will be very useful here. Becomes available in the next version of DokuWiki. https://github.com/splitbrain/dokuwiki/pull/3115
