### ISSUE TITLE
Index of the links referred at a page (WikidPad menu look-a-like)

### ISSUE THREAD

**Issue by aleth** [samuelet/indexmenu#88]
I have a feature request:

Would it be possible to add an option that would add the pages linked from a page as child nodes to the page in the tree? i.e. if page X contains links to Y and Z, then the entry for X in the indexmenu tree could be expanded to show Y and Z as children of X. (One might even do this recursively up to some maximum depth.)

This would be a nice way to include some of the implicit graph structure of the wiki that is not necessarily reflected in explicit namespaces.

**Comment by Klap-in** [comment]
I will not implement this feature, as it is a niche feature. If someone is interested, they could open a pull request with a proposal.
